### ISSUE TITLE
CentOS6.5报错求助。安装完成后在打开网页时报错

### ISSUE THREAD

**Issue by boailql** [zhangqichuan/CheungSSH#43]
Mod_python error: "PythonHandler django.core.handlers.modpython"

Traceback (most recent call last):

  File "/usr/lib64/python2.6/site-packages/mod_python/apache.py", line 421, in HandlerDispatch
    result = obj(req)

  File "/usr/lib/python2.6/site-packages/django/core/handlers/modpython.py", line 180, in handler
    return ModPythonHandler()(req)

  File "/usr/lib/python2.6/site-packages/django/core/handlers/modpython.py", line 142, in __call__
    self.load_middleware()

  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 43, in load_middleware
    mod = import_module(mw_module)

  File "/usr/lib/python2.6/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)

  File "/usr/lib/python2.6/site-packages/django/contrib/sessions/middleware.py", line 4, in <module>
    from django.utils.cache import patch_vary_headers

  File "/usr/lib/python2.6/site-packages/django/utils/cache.py", line 25, in <module>
    from django.core.cache import get_cache

  File "/usr/lib/python2.6/site-packages/django/core/cache/__init__.py", line 187, in <module>
    cache = get_cache(DEFAULT_CACHE_ALIAS)

  File "/usr/lib/python2.6/site-packages/django/core/cache/__init__.py", line 178, in get_cache
    "Could not find backend '%s': %s" % (backend, e))

InvalidCacheBackendError: Could not find backend 'redis_cache.cache.RedisCache': cannot import name DEFAULT_TIMEOUT

**Comment by jinliliu** [comment]
出现同样的问题
